### ISSUE TITLE
Incorrect naming convention or vector ngrams upload for FastText (SkipGram, 300 dim) in Google drive

### ISSUE THREAD

**Issue by FelSiq** [felipemaiapolo/legalnlp#2]
I believe the file `fasttext_cbow_size_300_window_15_epochs_20.wv.vectors_ngrams.npy` available at this project's Google drive is either incorrectly labeled as a result of "cbow" algorithm (see picture below) or was incorrectly uploaded in place of another file.

![Screen Shot 2022-10-21 at 22 58 52](https://user-images.githubusercontent.com/18670260/197313628-3ab4fc10-ad29-40ab-b06c-264e8917fcb7.png)

This makes the model fail to load:
```python
# gensim==4.2.0
import gensim.models
gensim.models.FastText.load("fasttext_sg_size_300_window_15_epochs_20")
```
```bash
FileNotFoundError: [Errno 2] No such file or directory: 'fasttext_sg_size_300_window_15_epochs_20.wv.vectors_ngrams.npy'
```

If the file was correctly uploaded, by simply renaming it from "cbow" to "sg" supposedly solves this issue, but I'm not sure if this is the case.

Could you please confirm this information?

Thanks in advance.

**Comment by felipemaiapolo** [comment]
Hi Felipe,

Thank you for pointing this out. We have fixed this issue and updated the file. Please let us know if you have further concerns.

Best,
Felipe
